### ISSUE TITLE
Reproducing RMSE result on "Original" images

### ISSUE THREAD

**Issue by LetiP** [DeepInsight-PCALab/ST-CGAN#6]
Hello! I am trying hard to reproduce your baseline, so your "Original" RMSE values of 32.67 on shadow regions, 6.83 on non-shadow, 10.97 on all.

![image](https://user-images.githubusercontent.com/16118202/48514937-c8035980-e85f-11e8-83eb-4ab2eb785d4d.png)

I downloaded your ISTD dataset from Google Drive, loaded the test images test_A and test_C and computed RMSE on them after converting them to LAB color space.

Why do I get values like 6.9 for "all" regions and not anything near your 10.97? Is there anything I do not understand from your paper?

Thanks in advance!

**Comment by LetiP** [comment]
Update: I get closer to your numbers, if I compute the RMSE in percentage on the RGB, not LAB space:
So:
shadow: 22.8%
non-shadow: 6.2%
all: 10.5%

It is still a mistery to me how to get the right numbers. Since it is only a computation on the original dataset and not a method evaluation.

**Comment by csjfwang** [comment]
Dear @LetiP,
Sorry to reply a little late.
It may be that the way we calculate the RMSE error is different, so our results are different.

The evaluation method and code we use are the same as that of GUO's CVPR11 paper.
You can email me (jfwang.cs at gmail.com). And I will provide you with the original evaluation code.

Thanks!
Jifeng.

**Comment by LetiP** [comment]
Thanks again for the code and for the quick response!

Perhaps as a clarification for others: In my opinion, the paper used not the RMSE (root mean squared error), but the MAE (mean absolute error). With the MAE, I am able to reproduce the results. :)

**Comment by nachifur** [comment]
@LetiP I found that the author has not answered questions for a long time. If it is convenient, can you send the evaluation code to my mailbox?
liujiawei@sia.cn
I will sincerely thank you for your help.
